api:
  version: 1

logging:
  config: classpath:logback.xml

# lets listen on all ports to ensure we can be invoked from the pod ip address
# contextPath: /api/v${api.version}/*
server:
  address: 0.0.0.0
  port: 8080

# =============================================
# spring configurations
# ---------------------------------------------
spring:
  application:
    name: cardiologist-api
  jpa:
    # log generated sql
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
    hibernate:
      ddl-auto: create-drop
  h2:
    # http://localhost:8080/h2-console
    # connection url: jdbc:h2:mem:testdb
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jackson:
    # JACKSON (JacksonProperties)
    # Date format string or a fully-qualified date format class name
    #spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      write_dates_as_timestamps: true

# =============================================
# spring actuator configurations
# ---------------------------------------------
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
      # if you want to change the default prometheus endpoint, just change the 'id' to another value.
      id: prometheus
  endpoints:
    web:
      exposure:
        include: ["*"]
  metrics:
    export:
      prometheus:
        enabled: true

# =============================================
# opentracing configurations
# ---------------------------------------------
opentracing:
  jaeger:
    enabled: true
    enable-b3-propagation: true
    log-spans: true
    const-sampler:
      decision: true
    http-sender:
      url: http://jaeger-collector:14268/api/traces

jaeger.tracer:
  host: jaeger-agent.microservices.svc
  port: 6831
